# Build stage
FROM maven:3.8.1-jdk-8-slim as maven

# Create folder for building the application
RUN mkdir /build

# Set it as workdir
WORKDIR /build

# Copy source files to the created folder
COPY pom.xml .
COPY src/ ./src

# Build and package the application
RUN mvn clean package


# Run stage
FROM adoptopenjdk/openjdk8:alpine-slim

# Create new folder for the app
RUN mkdir /app

# Copy application package to the newly created folder
COPY --from=maven /build/target/onlinestore-1.0.0.jar /app

# Expose port
EXPOSE 8080

# Run the application
ENTRYPOINT ["java", "-jar", "/app/onlinestore-1.0.0-SNAPSHOT.jar"]